// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: kvpb/kv.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Consistency int32

const (
	Consistency_CONSISTENCY_UNSPECIFIED Consistency = 0
	// Goes through Node.ReadIndex(): leader confirms leadership via a
	// majority heartbeat round before serving the read. Never stale.
	Consistency_CONSISTENCY_LINEARIZABLE Consistency = 1
	// Served from local state on whatever replica received the request.
	// May be stale on a partitioned or lagging follower — documented
	// tradeoff, not a bug.
	Consistency_CONSISTENCY_STALE Consistency = 2
)

// Enum value maps for Consistency.
var (
	Consistency_name = map[int32]string{
		0: "CONSISTENCY_UNSPECIFIED",
		1: "CONSISTENCY_LINEARIZABLE",
		2: "CONSISTENCY_STALE",
	}
	Consistency_value = map[string]int32{
		"CONSISTENCY_UNSPECIFIED":  0,
		"CONSISTENCY_LINEARIZABLE": 1,
		"CONSISTENCY_STALE":        2,
	}
)

func (x Consistency) Enum() *Consistency {
	p := new(Consistency)
	*p = x
	return p
}

func (x Consistency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Consistency) Descriptor() protoreflect.EnumDescriptor {
	return file_kvpb_kv_proto_enumTypes[0].Descriptor()
}

func (Consistency) Type() protoreflect.EnumType {
	return &file_kvpb_kv_proto_enumTypes[0]
}

func (x Consistency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Consistency.Descriptor instead.
func (Consistency) EnumDescriptor() ([]byte, []int) {
	return file_kvpb_kv_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Consistency   Consistency            `protobuf:"varint,3,opt,name=consistency,proto3,enum=kv.v1.Consistency" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_kvpb_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvpb_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_kvpb_kv_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetConsistency() Consistency {
	if x != nil {
		return x.Consistency
	}
	return Consistency_CONSISTENCY_UNSPECIFIED
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Value []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	// Set when this node is not the shard's leader and the request required
	// leader-only handling (e.g. LINEARIZABLE reads, or any write below).
	// Empty otherwise.
	LeaderHint    string `protobuf:"bytes,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_kvpb_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvpb_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kvpb_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_kvpb_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvpb_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_kvpb_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderHint    string                 `protobuf:"bytes,1,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_kvpb_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvpb_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_kvpb_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_kvpb_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvpb_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_kvpb_kv_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderHint    string                 `protobuf:"bytes,1,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_kvpb_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvpb_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_kvpb_kv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type CompareAndSwapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedValue []byte                 `protobuf:"bytes,3,opt,name=expected_value,json=expectedValue,proto3" json:"expected_value,omitempty"`
	ExpectAbsent  bool                   `protobuf:"varint,4,opt,name=expect_absent,json=expectAbsent,proto3" json:"expect_absent,omitempty"` // true means "only set if key does not currently exist"
	NewValue      []byte                 `protobuf:"bytes,5,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareAndSwapRequest) Reset() {
	*x = CompareAndSwapRequest{}
	mi := &file_kvpb_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareAndSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareAndSwapRequest) ProtoMessage() {}

func (x *CompareAndSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvpb_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareAndSwapRequest.ProtoReflect.Descriptor instead.
func (*CompareAndSwapRequest) Descriptor() ([]byte, []int) {
	return file_kvpb_kv_proto_rawDescGZIP(), []int{6}
}

func (x *CompareAndSwapRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *CompareAndSwapRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CompareAndSwapRequest) GetExpectedValue() []byte {
	if x != nil {
		return x.ExpectedValue
	}
	return nil
}

func (x *CompareAndSwapRequest) GetExpectAbsent() bool {
	if x != nil {
		return x.ExpectAbsent
	}
	return false
}

func (x *CompareAndSwapRequest) GetNewValue() []byte {
	if x != nil {
		return x.NewValue
	}
	return nil
}

type CompareAndSwapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Swapped       bool                   `protobuf:"varint,1,opt,name=swapped,proto3" json:"swapped,omitempty"`
	ActualValue   []byte                 `protobuf:"bytes,2,opt,name=actual_value,json=actualValue,proto3" json:"actual_value,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareAndSwapResponse) Reset() {
	*x = CompareAndSwapResponse{}
	mi := &file_kvpb_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareAndSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareAndSwapResponse) ProtoMessage() {}

func (x *CompareAndSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvpb_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareAndSwapResponse.ProtoReflect.Descriptor instead.
func (*CompareAndSwapResponse) Descriptor() ([]byte, []int) {
	return file_kvpb_kv_proto_rawDescGZIP(), []int{7}
}

func (x *CompareAndSwapResponse) GetSwapped() bool {
	if x != nil {
		return x.Swapped
	}
	return false
}

func (x *CompareAndSwapResponse) GetActualValue() []byte {
	if x != nil {
		return x.ActualValue
	}
	return nil
}

func (x *CompareAndSwapResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

var File_kvpb_kv_proto protoreflect.FileDescriptor

const file_kvpb_kv_proto_rawDesc = "" +
	"\n" +
	"\rkvpb/kv.proto\x12\x05kv.v1\"o\n" +
	"\n" +
	"GetRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x124\n" +
	"\vconsistency\x18\x03 \x01(\x0e2\x12.kv.v1.ConsistencyR\vconsistency\"Z\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\tR\n" +
	"leaderHint\"O\n" +
	"\n" +
	"PutRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\".\n" +
	"\vPutResponse\x12\x1f\n" +
	"\vleader_hint\x18\x01 \x01(\tR\n" +
	"leaderHint\"<\n" +
	"\rDeleteRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"1\n" +
	"\x0eDeleteResponse\x12\x1f\n" +
	"\vleader_hint\x18\x01 \x01(\tR\n" +
	"leaderHint\"\xad\x01\n" +
	"\x15CompareAndSwapRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12%\n" +
	"\x0eexpected_value\x18\x03 \x01(\fR\rexpectedValue\x12#\n" +
	"\rexpect_absent\x18\x04 \x01(\bR\fexpectAbsent\x12\x1b\n" +
	"\tnew_value\x18\x05 \x01(\fR\bnewValue\"v\n" +
	"\x16CompareAndSwapResponse\x12\x18\n" +
	"\aswapped\x18\x01 \x01(\bR\aswapped\x12!\n" +
	"\factual_value\x18\x02 \x01(\fR\vactualValue\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\tR\n" +
	"leaderHint*_\n" +
	"\vConsistency\x12\x1b\n" +
	"\x17CONSISTENCY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONSISTENCY_LINEARIZABLE\x10\x01\x12\x15\n" +
	"\x11CONSISTENCY_STALE\x10\x022\xed\x01\n" +
	"\tKVService\x12,\n" +
	"\x03Get\x12\x11.kv.v1.GetRequest\x1a\x12.kv.v1.GetResponse\x12,\n" +
	"\x03Put\x12\x11.kv.v1.PutRequest\x1a\x12.kv.v1.PutResponse\x125\n" +
	"\x06Delete\x12\x14.kv.v1.DeleteRequest\x1a\x15.kv.v1.DeleteResponse\x12M\n" +
	"\x0eCompareAndSwap\x12\x1c.kv.v1.CompareAndSwapRequest\x1a\x1d.kv.v1.CompareAndSwapResponseB4Z2github.com/SushantPotu/raft-kv-store/pkg/kvpb;kvpbb\x06proto3"

var (
	file_kvpb_kv_proto_rawDescOnce sync.Once
	file_kvpb_kv_proto_rawDescData []byte
)

func file_kvpb_kv_proto_rawDescGZIP() []byte {
	file_kvpb_kv_proto_rawDescOnce.Do(func() {
		file_kvpb_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvpb_kv_proto_rawDesc), len(file_kvpb_kv_proto_rawDesc)))
	})
	return file_kvpb_kv_proto_rawDescData
}

var file_kvpb_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kvpb_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kvpb_kv_proto_goTypes = []any{
	(Consistency)(0),               // 0: kv.v1.Consistency
	(*GetRequest)(nil),             // 1: kv.v1.GetRequest
	(*GetResponse)(nil),            // 2: kv.v1.GetResponse
	(*PutRequest)(nil),             // 3: kv.v1.PutRequest
	(*PutResponse)(nil),            // 4: kv.v1.PutResponse
	(*DeleteRequest)(nil),          // 5: kv.v1.DeleteRequest
	(*DeleteResponse)(nil),         // 6: kv.v1.DeleteResponse
	(*CompareAndSwapRequest)(nil),  // 7: kv.v1.CompareAndSwapRequest
	(*CompareAndSwapResponse)(nil), // 8: kv.v1.CompareAndSwapResponse
}
var file_kvpb_kv_proto_depIdxs = []int32{
	0, // 0: kv.v1.GetRequest.consistency:type_name -> kv.v1.Consistency
	1, // 1: kv.v1.KVService.Get:input_type -> kv.v1.GetRequest
	3, // 2: kv.v1.KVService.Put:input_type -> kv.v1.PutRequest
	5, // 3: kv.v1.KVService.Delete:input_type -> kv.v1.DeleteRequest
	7, // 4: kv.v1.KVService.CompareAndSwap:input_type -> kv.v1.CompareAndSwapRequest
	2, // 5: kv.v1.KVService.Get:output_type -> kv.v1.GetResponse
	4, // 6: kv.v1.KVService.Put:output_type -> kv.v1.PutResponse
	6, // 7: kv.v1.KVService.Delete:output_type -> kv.v1.DeleteResponse
	8, // 8: kv.v1.KVService.CompareAndSwap:output_type -> kv.v1.CompareAndSwapResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kvpb_kv_proto_init() }
func file_kvpb_kv_proto_init() {
	if File_kvpb_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvpb_kv_proto_rawDesc), len(file_kvpb_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvpb_kv_proto_goTypes,
		DependencyIndexes: file_kvpb_kv_proto_depIdxs,
		EnumInfos:         file_kvpb_kv_proto_enumTypes,
		MessageInfos:      file_kvpb_kv_proto_msgTypes,
	}.Build()
	File_kvpb_kv_proto = out.File
	file_kvpb_kv_proto_goTypes = nil
	file_kvpb_kv_proto_depIdxs = nil
}
