// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: metapb/meta.proto

package metapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShardDescriptor struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ShardId             string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	KeyRangeStart       []byte                 `protobuf:"bytes,2,opt,name=key_range_start,json=keyRangeStart,proto3" json:"key_range_start,omitempty"` // inclusive
	KeyRangeEnd         []byte                 `protobuf:"bytes,3,opt,name=key_range_end,json=keyRangeEnd,proto3" json:"key_range_end,omitempty"`       // exclusive; empty means "no upper bound"
	Replicas            []*ReplicaDescriptor   `protobuf:"bytes,4,rep,name=replicas,proto3" json:"replicas,omitempty"`
	CurrentLeaderNodeId string                 `protobuf:"bytes,5,opt,name=current_leader_node_id,json=currentLeaderNodeId,proto3" json:"current_leader_node_id,omitempty"`
	CurrentLeaderTerm   uint64                 `protobuf:"varint,6,opt,name=current_leader_term,json=currentLeaderTerm,proto3" json:"current_leader_term,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ShardDescriptor) Reset() {
	*x = ShardDescriptor{}
	mi := &file_metapb_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardDescriptor) ProtoMessage() {}

func (x *ShardDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardDescriptor.ProtoReflect.Descriptor instead.
func (*ShardDescriptor) Descriptor() ([]byte, []int) {
	return file_metapb_meta_proto_rawDescGZIP(), []int{0}
}

func (x *ShardDescriptor) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardDescriptor) GetKeyRangeStart() []byte {
	if x != nil {
		return x.KeyRangeStart
	}
	return nil
}

func (x *ShardDescriptor) GetKeyRangeEnd() []byte {
	if x != nil {
		return x.KeyRangeEnd
	}
	return nil
}

func (x *ShardDescriptor) GetReplicas() []*ReplicaDescriptor {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *ShardDescriptor) GetCurrentLeaderNodeId() string {
	if x != nil {
		return x.CurrentLeaderNodeId
	}
	return ""
}

func (x *ShardDescriptor) GetCurrentLeaderTerm() uint64 {
	if x != nil {
		return x.CurrentLeaderTerm
	}
	return 0
}

type ReplicaDescriptor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address          string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // host:port, resolved via service discovery
	AvailabilityZone string                 `protobuf:"bytes,3,opt,name=availability_zone,json=availabilityZone,proto3" json:"availability_zone,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplicaDescriptor) Reset() {
	*x = ReplicaDescriptor{}
	mi := &file_metapb_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaDescriptor) ProtoMessage() {}

func (x *ReplicaDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaDescriptor.ProtoReflect.Descriptor instead.
func (*ReplicaDescriptor) Descriptor() ([]byte, []int) {
	return file_metapb_meta_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicaDescriptor) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReplicaDescriptor) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ReplicaDescriptor) GetAvailabilityZone() string {
	if x != nil {
		return x.AvailabilityZone
	}
	return ""
}

type GetShardForKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardForKeyRequest) Reset() {
	*x = GetShardForKeyRequest{}
	mi := &file_metapb_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardForKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardForKeyRequest) ProtoMessage() {}

func (x *GetShardForKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardForKeyRequest.ProtoReflect.Descriptor instead.
func (*GetShardForKeyRequest) Descriptor() ([]byte, []int) {
	return file_metapb_meta_proto_rawDescGZIP(), []int{2}
}

func (x *GetShardForKeyRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetShardForKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         *ShardDescriptor       `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardForKeyResponse) Reset() {
	*x = GetShardForKeyResponse{}
	mi := &file_metapb_meta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardForKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardForKeyResponse) ProtoMessage() {}

func (x *GetShardForKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_meta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardForKeyResponse.ProtoReflect.Descriptor instead.
func (*GetShardForKeyResponse) Descriptor() ([]byte, []int) {
	return file_metapb_meta_proto_rawDescGZIP(), []int{3}
}

func (x *GetShardForKeyResponse) GetShard() *ShardDescriptor {
	if x != nil {
		return x.Shard
	}
	return nil
}

type ListShardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShardsRequest) Reset() {
	*x = ListShardsRequest{}
	mi := &file_metapb_meta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShardsRequest) ProtoMessage() {}

func (x *ListShardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_meta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShardsRequest.ProtoReflect.Descriptor instead.
func (*ListShardsRequest) Descriptor() ([]byte, []int) {
	return file_metapb_meta_proto_rawDescGZIP(), []int{4}
}

type ListShardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shards        []*ShardDescriptor     `protobuf:"bytes,1,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShardsResponse) Reset() {
	*x = ListShardsResponse{}
	mi := &file_metapb_meta_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShardsResponse) ProtoMessage() {}

func (x *ListShardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_meta_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShardsResponse.ProtoReflect.Descriptor instead.
func (*ListShardsResponse) Descriptor() ([]byte, []int) {
	return file_metapb_meta_proto_rawDescGZIP(), []int{5}
}

func (x *ListShardsResponse) GetShards() []*ShardDescriptor {
	if x != nil {
		return x.Shards
	}
	return nil
}

type ReportLeaderChangeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShardId         string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	NewLeaderNodeId string                 `protobuf:"bytes,2,opt,name=new_leader_node_id,json=newLeaderNodeId,proto3" json:"new_leader_node_id,omitempty"`
	Term            uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportLeaderChangeRequest) Reset() {
	*x = ReportLeaderChangeRequest{}
	mi := &file_metapb_meta_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportLeaderChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportLeaderChangeRequest) ProtoMessage() {}

func (x *ReportLeaderChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_meta_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportLeaderChangeRequest.ProtoReflect.Descriptor instead.
func (*ReportLeaderChangeRequest) Descriptor() ([]byte, []int) {
	return file_metapb_meta_proto_rawDescGZIP(), []int{6}
}

func (x *ReportLeaderChangeRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ReportLeaderChangeRequest) GetNewLeaderNodeId() string {
	if x != nil {
		return x.NewLeaderNodeId
	}
	return ""
}

func (x *ReportLeaderChangeRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type ReportLeaderChangeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False if this report was rejected because a newer term is already
	// recorded (conditional-write guard against stale reports).
	Accepted            bool   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	CurrentTermOnRecord uint64 `protobuf:"varint,2,opt,name=current_term_on_record,json=currentTermOnRecord,proto3" json:"current_term_on_record,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReportLeaderChangeResponse) Reset() {
	*x = ReportLeaderChangeResponse{}
	mi := &file_metapb_meta_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportLeaderChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportLeaderChangeResponse) ProtoMessage() {}

func (x *ReportLeaderChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_meta_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportLeaderChangeResponse.ProtoReflect.Descriptor instead.
func (*ReportLeaderChangeResponse) Descriptor() ([]byte, []int) {
	return file_metapb_meta_proto_rawDescGZIP(), []int{7}
}

func (x *ReportLeaderChangeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportLeaderChangeResponse) GetCurrentTermOnRecord() uint64 {
	if x != nil {
		return x.CurrentTermOnRecord
	}
	return 0
}

type RegisterReplicaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Replica       *ReplicaDescriptor     `protobuf:"bytes,2,opt,name=replica,proto3" json:"replica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReplicaRequest) Reset() {
	*x = RegisterReplicaRequest{}
	mi := &file_metapb_meta_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReplicaRequest) ProtoMessage() {}

func (x *RegisterReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_meta_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReplicaRequest.ProtoReflect.Descriptor instead.
func (*RegisterReplicaRequest) Descriptor() ([]byte, []int) {
	return file_metapb_meta_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterReplicaRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *RegisterReplicaRequest) GetReplica() *ReplicaDescriptor {
	if x != nil {
		return x.Replica
	}
	return nil
}

type RegisterReplicaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReplicaResponse) Reset() {
	*x = RegisterReplicaResponse{}
	mi := &file_metapb_meta_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReplicaResponse) ProtoMessage() {}

func (x *RegisterReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_meta_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReplicaResponse.ProtoReflect.Descriptor instead.
func (*RegisterReplicaResponse) Descriptor() ([]byte, []int) {
	return file_metapb_meta_proto_rawDescGZIP(), []int{9}
}

var File_metapb_meta_proto protoreflect.FileDescriptor

const file_metapb_meta_proto_rawDesc = "" +
	"\n" +
	"\x11metapb/meta.proto\x12\ameta.v1\"\x95\x02\n" +
	"\x0fShardDescriptor\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12&\n" +
	"\x0fkey_range_start\x18\x02 \x01(\fR\rkeyRangeStart\x12\"\n" +
	"\rkey_range_end\x18\x03 \x01(\fR\vkeyRangeEnd\x126\n" +
	"\breplicas\x18\x04 \x03(\v2\x1a.meta.v1.ReplicaDescriptorR\breplicas\x123\n" +
	"\x16current_leader_node_id\x18\x05 \x01(\tR\x13currentLeaderNodeId\x12.\n" +
	"\x13current_leader_term\x18\x06 \x01(\x04R\x11currentLeaderTerm\"s\n" +
	"\x11ReplicaDescriptor\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12+\n" +
	"\x11availability_zone\x18\x03 \x01(\tR\x10availabilityZone\")\n" +
	"\x15GetShardForKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"H\n" +
	"\x16GetShardForKeyResponse\x12.\n" +
	"\x05shard\x18\x01 \x01(\v2\x18.meta.v1.ShardDescriptorR\x05shard\"\x13\n" +
	"\x11ListShardsRequest\"F\n" +
	"\x12ListShardsResponse\x120\n" +
	"\x06shards\x18\x01 \x03(\v2\x18.meta.v1.ShardDescriptorR\x06shards\"w\n" +
	"\x19ReportLeaderChangeRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12+\n" +
	"\x12new_leader_node_id\x18\x02 \x01(\tR\x0fnewLeaderNodeId\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\"m\n" +
	"\x1aReportLeaderChangeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x123\n" +
	"\x16current_term_on_record\x18\x02 \x01(\x04R\x13currentTermOnRecord\"i\n" +
	"\x16RegisterReplicaRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x124\n" +
	"\areplica\x18\x02 \x01(\v2\x1a.meta.v1.ReplicaDescriptorR\areplica\"\x19\n" +
	"\x17RegisterReplicaResponse2\xe0\x02\n" +
	"\x0fMetadataService\x12Q\n" +
	"\x0eGetShardForKey\x12\x1e.meta.v1.GetShardForKeyRequest\x1a\x1f.meta.v1.GetShardForKeyResponse\x12E\n" +
	"\n" +
	"ListShards\x12\x1a.meta.v1.ListShardsRequest\x1a\x1b.meta.v1.ListShardsResponse\x12]\n" +
	"\x12ReportLeaderChange\x12\".meta.v1.ReportLeaderChangeRequest\x1a#.meta.v1.ReportLeaderChangeResponse\x12T\n" +
	"\x0fRegisterReplica\x12\x1f.meta.v1.RegisterReplicaRequest\x1a .meta.v1.RegisterReplicaResponseB8Z6github.com/SushantPotu/raft-kv-store/pkg/metapb;metapbb\x06proto3"

var (
	file_metapb_meta_proto_rawDescOnce sync.Once
	file_metapb_meta_proto_rawDescData []byte
)

func file_metapb_meta_proto_rawDescGZIP() []byte {
	file_metapb_meta_proto_rawDescOnce.Do(func() {
		file_metapb_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metapb_meta_proto_rawDesc), len(file_metapb_meta_proto_rawDesc)))
	})
	return file_metapb_meta_proto_rawDescData
}

var file_metapb_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_metapb_meta_proto_goTypes = []any{
	(*ShardDescriptor)(nil),            // 0: meta.v1.ShardDescriptor
	(*ReplicaDescriptor)(nil),          // 1: meta.v1.ReplicaDescriptor
	(*GetShardForKeyRequest)(nil),      // 2: meta.v1.GetShardForKeyRequest
	(*GetShardForKeyResponse)(nil),     // 3: meta.v1.GetShardForKeyResponse
	(*ListShardsRequest)(nil),          // 4: meta.v1.ListShardsRequest
	(*ListShardsResponse)(nil),         // 5: meta.v1.ListShardsResponse
	(*ReportLeaderChangeRequest)(nil),  // 6: meta.v1.ReportLeaderChangeRequest
	(*ReportLeaderChangeResponse)(nil), // 7: meta.v1.ReportLeaderChangeResponse
	(*RegisterReplicaRequest)(nil),     // 8: meta.v1.RegisterReplicaRequest
	(*RegisterReplicaResponse)(nil),    // 9: meta.v1.RegisterReplicaResponse
}
var file_metapb_meta_proto_depIdxs = []int32{
	1, // 0: meta.v1.ShardDescriptor.replicas:type_name -> meta.v1.ReplicaDescriptor
	0, // 1: meta.v1.GetShardForKeyResponse.shard:type_name -> meta.v1.ShardDescriptor
	0, // 2: meta.v1.ListShardsResponse.shards:type_name -> meta.v1.ShardDescriptor
	1, // 3: meta.v1.RegisterReplicaRequest.replica:type_name -> meta.v1.ReplicaDescriptor
	2, // 4: meta.v1.MetadataService.GetShardForKey:input_type -> meta.v1.GetShardForKeyRequest
	4, // 5: meta.v1.MetadataService.ListShards:input_type -> meta.v1.ListShardsRequest
	6, // 6: meta.v1.MetadataService.ReportLeaderChange:input_type -> meta.v1.ReportLeaderChangeRequest
	8, // 7: meta.v1.MetadataService.RegisterReplica:input_type -> meta.v1.RegisterReplicaRequest
	3, // 8: meta.v1.MetadataService.GetShardForKey:output_type -> meta.v1.GetShardForKeyResponse
	5, // 9: meta.v1.MetadataService.ListShards:output_type -> meta.v1.ListShardsResponse
	7, // 10: meta.v1.MetadataService.ReportLeaderChange:output_type -> meta.v1.ReportLeaderChangeResponse
	9, // 11: meta.v1.MetadataService.RegisterReplica:output_type -> meta.v1.RegisterReplicaResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_metapb_meta_proto_init() }
func file_metapb_meta_proto_init() {
	if File_metapb_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metapb_meta_proto_rawDesc), len(file_metapb_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metapb_meta_proto_goTypes,
		DependencyIndexes: file_metapb_meta_proto_depIdxs,
		MessageInfos:      file_metapb_meta_proto_msgTypes,
	}.Build()
	File_metapb_meta_proto = out.File
	file_metapb_meta_proto_goTypes = nil
	file_metapb_meta_proto_depIdxs = nil
}
