// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: metapb/meta.proto

package metapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataService_GetShardForKey_FullMethodName     = "/meta.v1.MetadataService/GetShardForKey"
	MetadataService_ListShards_FullMethodName         = "/meta.v1.MetadataService/ListShards"
	MetadataService_ReportLeaderChange_FullMethodName = "/meta.v1.MetadataService/ReportLeaderChange"
	MetadataService_RegisterReplica_FullMethodName    = "/meta.v1.MetadataService/RegisterReplica"
)

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetadataService is the cluster's source of truth for "which shard owns
// this key, and who is its current leader". Backed by DynamoDB in
// production (see internal/metaservice). kvrouter treats this as the
// authoritative source and its own in-memory leader-hint cache as a
// self-healing optimization on top — never the other way around.
type MetadataServiceClient interface {
	GetShardForKey(ctx context.Context, in *GetShardForKeyRequest, opts ...grpc.CallOption) (*GetShardForKeyResponse, error)
	ListShards(ctx context.Context, in *ListShardsRequest, opts ...grpc.CallOption) (*ListShardsResponse, error)
	// Called by a kvnode when it becomes (or stops being) leader for a shard,
	// so metaservice's record stays close to real-time. Uses a
	// conditional write keyed on term so a stale/delayed report from an
	// old leader can never clobber a newer leader's record.
	ReportLeaderChange(ctx context.Context, in *ReportLeaderChangeRequest, opts ...grpc.CallOption) (*ReportLeaderChangeResponse, error)
	// Called by a kvnode at startup to register itself as a replica for a
	// shard (used alongside Cloud Map service discovery for reachability).
	RegisterReplica(ctx context.Context, in *RegisterReplicaRequest, opts ...grpc.CallOption) (*RegisterReplicaResponse, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) GetShardForKey(ctx context.Context, in *GetShardForKeyRequest, opts ...grpc.CallOption) (*GetShardForKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShardForKeyResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetShardForKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ListShards(ctx context.Context, in *ListShardsRequest, opts ...grpc.CallOption) (*ListShardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShardsResponse)
	err := c.cc.Invoke(ctx, MetadataService_ListShards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ReportLeaderChange(ctx context.Context, in *ReportLeaderChangeRequest, opts ...grpc.CallOption) (*ReportLeaderChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportLeaderChangeResponse)
	err := c.cc.Invoke(ctx, MetadataService_ReportLeaderChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) RegisterReplica(ctx context.Context, in *RegisterReplicaRequest, opts ...grpc.CallOption) (*RegisterReplicaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterReplicaResponse)
	err := c.cc.Invoke(ctx, MetadataService_RegisterReplica_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility.
//
// MetadataService is the cluster's source of truth for "which shard owns
// this key, and who is its current leader". Backed by DynamoDB in
// production (see internal/metaservice). kvrouter treats this as the
// authoritative source and its own in-memory leader-hint cache as a
// self-healing optimization on top — never the other way around.
type MetadataServiceServer interface {
	GetShardForKey(context.Context, *GetShardForKeyRequest) (*GetShardForKeyResponse, error)
	ListShards(context.Context, *ListShardsRequest) (*ListShardsResponse, error)
	// Called by a kvnode when it becomes (or stops being) leader for a shard,
	// so metaservice's record stays close to real-time. Uses a
	// conditional write keyed on term so a stale/delayed report from an
	// old leader can never clobber a newer leader's record.
	ReportLeaderChange(context.Context, *ReportLeaderChangeRequest) (*ReportLeaderChangeResponse, error)
	// Called by a kvnode at startup to register itself as a replica for a
	// shard (used alongside Cloud Map service discovery for reachability).
	RegisterReplica(context.Context, *RegisterReplicaRequest) (*RegisterReplicaResponse, error)
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataServiceServer struct{}

func (UnimplementedMetadataServiceServer) GetShardForKey(context.Context, *GetShardForKeyRequest) (*GetShardForKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShardForKey not implemented")
}
func (UnimplementedMetadataServiceServer) ListShards(context.Context, *ListShardsRequest) (*ListShardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShards not implemented")
}
func (UnimplementedMetadataServiceServer) ReportLeaderChange(context.Context, *ReportLeaderChangeRequest) (*ReportLeaderChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportLeaderChange not implemented")
}
func (UnimplementedMetadataServiceServer) RegisterReplica(context.Context, *RegisterReplicaRequest) (*RegisterReplicaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterReplica not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}
func (UnimplementedMetadataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	// If the following call panics, it indicates UnimplementedMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_GetShardForKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShardForKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetShardForKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetShardForKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetShardForKey(ctx, req.(*GetShardForKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ListShards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ListShards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_ListShards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ListShards(ctx, req.(*ListShardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ReportLeaderChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportLeaderChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ReportLeaderChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_ReportLeaderChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ReportLeaderChange(ctx, req.(*ReportLeaderChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_RegisterReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReplicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).RegisterReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_RegisterReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).RegisterReplica(ctx, req.(*RegisterReplicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meta.v1.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShardForKey",
			Handler:    _MetadataService_GetShardForKey_Handler,
		},
		{
			MethodName: "ListShards",
			Handler:    _MetadataService_ListShards_Handler,
		},
		{
			MethodName: "ReportLeaderChange",
			Handler:    _MetadataService_ReportLeaderChange_Handler,
		},
		{
			MethodName: "RegisterReplica",
			Handler:    _MetadataService_RegisterReplica_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metapb/meta.proto",
}
