// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: raftpb/raft.proto

package raftpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftTransportService_Send_FullMethodName            = "/raft.v1.RaftTransportService/Send"
	RaftTransportService_InstallSnapshot_FullMethodName = "/raft.v1.RaftTransportService/InstallSnapshot"
)

// RaftTransportServiceClient is the client API for RaftTransportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RaftTransportService carries peer-to-peer consensus RPCs between nodes
// hosting the same shard's Raft group.
//
// Design note (added at Integration Checkpoint 1, after the original
// per-RPC-type design — RequestVote/AppendEntries each a unary call
// synchronously returning their own Response type — turned out not to
// match how raft.Node actually behaves): Node never produces a reply
// synchronously from Step. A reply to an inbound RequestVote or
// AppendEntries is just another outbound raft.Message — carrying a
// Response-typed payload, addressed back to the original sender — queued
// for a *later* Ready() call, exactly like any other message (see
// pkg/raft/types.go's Message/InboundMessage doc comments, and
// internal/raft/election.go / replication.go, which both call n.send(from,
// kind, &raftpb.XxxResponse{...}) to reply). A synchronous unary RPC
// shaped "send a request, get a response back on the same call" cannot
// carry that: the real response doesn't exist yet when the request
// arrives, and by the time it does exist, it needs to travel as its own
// outbound send back to the original requester — not as this call's
// return value.
//
// So every Raft protocol message (request or response, either direction)
// travels through the single Send RPC below as a RaftMessage envelope,
// fire-and-forget (returns Empty; the real reply, if any, arrives later as
// its own separate Send call in the other direction and is fed into the
// receiver's own Node via Step, same as everything else). This matches
// Node's actual internal model exactly, and is the same shape etcd/raft's
// own transport (rafthttp) uses: peers just POST raftpb.Message envelopes
// at each other.
type RaftTransportServiceClient interface {
	Send(ctx context.Context, in *RaftMessage, opts ...grpc.CallOption) (*SendAck, error)
	// InstallSnapshot is kept as its own client-streaming RPC (unlike Send
	// above) because a full-keyspace snapshot can be too large for one
	// message and needs to be chunked. This call's own synchronous
	// completion is NOT the real InstallSnapshotResponse — Node produces
	// that the same asynchronous way as every other reply, delivered back
	// via a later Send call — callers must not rely on this RPC's return
	// value for anything beyond "every chunk was received by the transport."
	InstallSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InstallSnapshotChunk, InstallSnapshotAck], error)
}

type raftTransportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftTransportServiceClient(cc grpc.ClientConnInterface) RaftTransportServiceClient {
	return &raftTransportServiceClient{cc}
}

func (c *raftTransportServiceClient) Send(ctx context.Context, in *RaftMessage, opts ...grpc.CallOption) (*SendAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendAck)
	err := c.cc.Invoke(ctx, RaftTransportService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftTransportServiceClient) InstallSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InstallSnapshotChunk, InstallSnapshotAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RaftTransportService_ServiceDesc.Streams[0], RaftTransportService_InstallSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstallSnapshotChunk, InstallSnapshotAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftTransportService_InstallSnapshotClient = grpc.ClientStreamingClient[InstallSnapshotChunk, InstallSnapshotAck]

// RaftTransportServiceServer is the server API for RaftTransportService service.
// All implementations must embed UnimplementedRaftTransportServiceServer
// for forward compatibility.
//
// RaftTransportService carries peer-to-peer consensus RPCs between nodes
// hosting the same shard's Raft group.
//
// Design note (added at Integration Checkpoint 1, after the original
// per-RPC-type design — RequestVote/AppendEntries each a unary call
// synchronously returning their own Response type — turned out not to
// match how raft.Node actually behaves): Node never produces a reply
// synchronously from Step. A reply to an inbound RequestVote or
// AppendEntries is just another outbound raft.Message — carrying a
// Response-typed payload, addressed back to the original sender — queued
// for a *later* Ready() call, exactly like any other message (see
// pkg/raft/types.go's Message/InboundMessage doc comments, and
// internal/raft/election.go / replication.go, which both call n.send(from,
// kind, &raftpb.XxxResponse{...}) to reply). A synchronous unary RPC
// shaped "send a request, get a response back on the same call" cannot
// carry that: the real response doesn't exist yet when the request
// arrives, and by the time it does exist, it needs to travel as its own
// outbound send back to the original requester — not as this call's
// return value.
//
// So every Raft protocol message (request or response, either direction)
// travels through the single Send RPC below as a RaftMessage envelope,
// fire-and-forget (returns Empty; the real reply, if any, arrives later as
// its own separate Send call in the other direction and is fed into the
// receiver's own Node via Step, same as everything else). This matches
// Node's actual internal model exactly, and is the same shape etcd/raft's
// own transport (rafthttp) uses: peers just POST raftpb.Message envelopes
// at each other.
type RaftTransportServiceServer interface {
	Send(context.Context, *RaftMessage) (*SendAck, error)
	// InstallSnapshot is kept as its own client-streaming RPC (unlike Send
	// above) because a full-keyspace snapshot can be too large for one
	// message and needs to be chunked. This call's own synchronous
	// completion is NOT the real InstallSnapshotResponse — Node produces
	// that the same asynchronous way as every other reply, delivered back
	// via a later Send call — callers must not rely on this RPC's return
	// value for anything beyond "every chunk was received by the transport."
	InstallSnapshot(grpc.ClientStreamingServer[InstallSnapshotChunk, InstallSnapshotAck]) error
	mustEmbedUnimplementedRaftTransportServiceServer()
}

// UnimplementedRaftTransportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftTransportServiceServer struct{}

func (UnimplementedRaftTransportServiceServer) Send(context.Context, *RaftMessage) (*SendAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedRaftTransportServiceServer) InstallSnapshot(grpc.ClientStreamingServer[InstallSnapshotChunk, InstallSnapshotAck]) error {
	return status.Error(codes.Unimplemented, "method InstallSnapshot not implemented")
}
func (UnimplementedRaftTransportServiceServer) mustEmbedUnimplementedRaftTransportServiceServer() {}
func (UnimplementedRaftTransportServiceServer) testEmbeddedByValue()                              {}

// UnsafeRaftTransportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftTransportServiceServer will
// result in compilation errors.
type UnsafeRaftTransportServiceServer interface {
	mustEmbedUnimplementedRaftTransportServiceServer()
}

func RegisterRaftTransportServiceServer(s grpc.ServiceRegistrar, srv RaftTransportServiceServer) {
	// If the following call panics, it indicates UnimplementedRaftTransportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftTransportService_ServiceDesc, srv)
}

func _RaftTransportService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftTransportServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftTransportService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftTransportServiceServer).Send(ctx, req.(*RaftMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftTransportService_InstallSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftTransportServiceServer).InstallSnapshot(&grpc.GenericServerStream[InstallSnapshotChunk, InstallSnapshotAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftTransportService_InstallSnapshotServer = grpc.ClientStreamingServer[InstallSnapshotChunk, InstallSnapshotAck]

// RaftTransportService_ServiceDesc is the grpc.ServiceDesc for RaftTransportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftTransportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raft.v1.RaftTransportService",
	HandlerType: (*RaftTransportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _RaftTransportService_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InstallSnapshot",
			Handler:       _RaftTransportService_InstallSnapshot_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "raftpb/raft.proto",
}
